- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  vars:
    daemon_json:
      bip: 192.168.99.1/24
      default-runtime: nvidia
      runtimes:
        nvidia:
          path: /usr/bin/nvidia-container-runtime
          runtimeArgs: []
  tasks:
    - name: docker | apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: nvidia-docker | apt key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present

    - name: docker | apt repo
      apt_repository: 
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: nvidia-docker | apt repo
      apt_repository:
        repo: "{{ item }}"
        state: present
        filename: 'nvidia-docker'
        update_cache: yes
      with_items:
        - "deb https://nvidia.github.io/libnvidia-container/ubuntu16.04/amd64 /"
        - "deb https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/amd64 /"
        - "deb https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64 /"

    - name: nvidia-docker | install
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - nvidia-docker2
          - nvidia-container-runtime

    - name: set docker default runtime
      copy:
        content: "{{ daemon_json | to_nice_json }}"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644

    - name: docker | restart service
      service: name=docker state=restarted enabled=yes

    - name: clone a git repository
      git: 
        repo: "https://github.com/EJSohn/nvidia-packer-docker-ansible.git"
        dest: /var/www/
        version: master